datamodel/objects/Movie_Review__c/Movie_Review__c.object-meta.xml
<CustomObject>
    <label>Movie Review</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Movie Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movie Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

datamodel/objects/Movie_Review__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <label>Review</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

datamodel/objects/Movie_Review__c/fields/Visibility__c.field-meta.xml
<CustomField>
    <fullName>Visibility__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Visibility</label>
    <type>Checkbox</type>
</CustomField>

reviewer/main/default/classes/HelperClassToHideReview.cls
public with sharing class HelperClassToHideReview {
  public static List<Movie_Review__c> makeData(Id recordId) {
    List<Movie_Review__c> reviews = new List<Movie_Review__c>();
    Movie_Review__c movRev = [
      SELECT Id, Review__c, Visibility__c
      FROM Movie_Review__c
      WHERE Id = :recordId AND Visibility__c = TRUE
    ];
    reviews.add(movRev);
    return reviews;
  }
  @AuraEnabled(cacheable=true)
  public static List<Movie_Review__c> getRecordWithVisibleReview(Id recordId) {
    List<Movie_Review__c> results = makeData(recordId);
    return results;
  }
  @AuraEnabled
  public static List<Movie_Review__c> hideReview(Id recordId) {
    List<Movie_Review__c> results = makeData(recordId);
    MovieReviewService.hideReview(results);
    return results;
  }
}